name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Run tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.145.193.115
          username: chatbot.pem
          key: ssh -i "chatbot.pem" ubuntu@ec2-54-145-193-115.compute-1.amazonaws.com
          script: |
            cd /home/ubuntu/Ova-Assignment-DEVOPS-bhawanak0504
            git pull origin main
            python app.py  # Restart your Flask application
