name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install Flask
          pip install Jinja2
          pip install Werkzeug
          pip install MarkupSafe
          pip install itsdangerous
          pip install click
          
      - name: Run tests
        run: |
           pip install pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.145.193.115
          username: ubuntu

          script: |
            cd /home/ubuntu/Ova-Assignment-DEVOPS-bhawanak0504
            git pull origin main
            python3 app.py  # Restart your Flask application
