name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install Flask
          pip install Jinja2
          pip install Werkzeug
          pip install MarkupSafe
          pip install itsdangerous
          pip install click
          
      - name: Run tests
        run: |
           pip install pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.145.193.115
          username: ubuntu
          key: MIIEowIBAAKCAQEAt1FcpR3godDhNHglIblzt7hjy5fWnfm46OYJ/nu7qqGfk6GG
               k68MjDvnxyqQIm3jRtKyHKzjlJUZOYsmhiwzf/3//7zVoBCqpmlHmHeMwkw+H4PM
               PkS91rMS5+0BflaHXBAleCZJSJRXrPeHPbDIymo16T/AMyprcpli5EFu9X1dkVjm
               yxMV3lfCEYQS3PE0Nx8LfwHNnc8FoU7WQ0mRlFi7iTHr53vW0oNPhEX/yHzk8bDV
               EWYHZYOLAANcygRESPNqDojllm0Vud1+FYXM8im9/62grzVEIfchH5hN+9w7Hfm8
               TZjfKatmGEgRLTnzkHexims6MJ8l7r7p2inHOQIDAQABAoIBACh44RBfQUnYePAB
               mokQjZjBL98yHaLxED7zEr/Jh4xLdJS+c5zFZ+rKCwjwv7OqOSRYvhQQo4oZROFs
               dEvpFFGsvUkz4qIdK9/jnHfv5Pa8qHaCvaP9vz/Yd1MXA15mMipEMlGNel54ycaZ
               O5WGIz51JoPhnEhvlBtP/AJS4/F0pRoZPhKZnVEYo114LFvh3eFr243Xa54IKXst
               YduroWcvQIeViemifEb4i7N+Y20o+qZQ5N2Xyj9D5cMI1lSKRK42tilLGvaN1e+N
               sbfZuEXzrgLCFuSbyqtMGV9kcWsYux+kEN8blFMwI+Ba0E0ttv9UtIzAToVTf7LM
               qsj1qsUCgYEA7PxGJ5klPSui+vlKo47UCcMi+cT0rZhhUwkqoohoWgUaKIxYH9NG
               HAAAfVxL3unt6ZR7eFXGc/rVdzBArImwYNoEBHXpqSZQ26VWWrdVNOiBmL6YY24k
               BSs1dxLgRnffrLLk2ODNsNivLkhHEwYED0xuTQEIcVlUBoagu57pGXcCgYEAxga+
               oZ15AN3Fj2mw6yw+24T+BBK2GlDpJno5l5+tTfHIaF4/4ILj5rXnkhbQMojz3uiV
               ktRYt90CdG8p8Dj08aHdySMMHUBOrbuA1asX8gMumGR8IVcHq0vqwNRes2S88jNB
               v66aiQPITj0NIuJLxliZ6Ud23HyZSjfu8phPUM8CgYEA4IczwJisW4RYagh+2u+b
              nZQwMwyT9VUGALISnuM2WvOykPBHHgAB0M1/qUYk7BIewstXH+/EkmX4kXA6Fj5t
              yZVFcSR2OTiAK1o+srw4EmSnRJxvrOTRY8RIZ4SO0LUKSolDoOd8ei0R7Hu2OyPb
              /NKhPnvYD+xeW8B50MkCeIkCgYBPOSWM7L4bLZ47GNKR01q2Ygdpw76c2p/cJ+vg
              kB46X6+IqaQugs8AXuftFzll7kp6dFxaqJ9xt3ai9FI36+F6xgI/1Mik7zRK5wfM
              860ZwlIi35iVkgbcbfvV92CHrpa04vK75/OlOyEow938hcJA8PNqU4/m9+Yvvh7X
              aT3aGwKBgBGSCJJhhnVtkCx6o8sPwuSy9stxNJmFZ+3nJkA4wh7qUbJS5LHhqSgg
              kyctVVSPwNJUBd3Y1gx8OMEP0nbwdBRC1erO5QriPjGxfa2kMV29mWns/uS5xzMQ
              Vta19OI8OvghQLDcLB8daGoqZtDZGv4FmIeMXIODbJUCaq92uRXJ

          script: |
            cd /home/ubuntu/Ova-Assignment-DEVOPS-bhawanak0504
            git pull origin main
            python3 app.py  # Restart your Flask application
